server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/IMENDOZA21/ms-course-youtube.git
          searchPaths: config-data
          username: ${GIT_USER:IMENDOZA21}
          password: ${GIT_PASSWORD:bbYtsIJB:v1}
          default-label: ms-course-youtube
        default-label: ms-course-youtube

  security:
    user:
      name: root
      password: s3cr3t
